# Generated by Django 2.2 on 2019-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='copy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备份'),
        ),
        migrations.AddField(
            model_name='site',
            name='is_select',
            field=models.BooleanField(default=True, verbose_name='是否选择'),
        ),
    ]
