# Generated by Django 2.2 on 2019-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190713_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='oversear',
            field=models.BooleanField(default=False, verbose_name='长响应站点'),
        ),
    ]
