# Generated by Django 2.2 on 2019-07-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_site_oversear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='oversear',
            new_name='overseas',
        ),
    ]
